# Site settings
title: ButterFlying
description: 梦想总是要有的，万一实现了呢
favicon: /assets/img/avatar.JPG
baseurl:
url: https://butterflying.github.io
rss_url:

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/Hefei

markdown: kramdown
port: 5020
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
